services:

  postgres:
    image: postgres:17-alpine
    container_name: airline-postgres
    environment:
      POSTGRES_USER: airline
      POSTGRES_PASSWORD: airline
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U airline -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  postgres-data:
